"""Public platform domain contracts, versioned independently from persistence."""

from .artifacts import ArtifactKind, ArtifactManifest
from .base import SCHEMA_VERSION, ContentHash, StrictContract, VersionedContract, Weight
from .crypto import (
    CryptoLiquidityMetrics,
    CryptoQualityThresholds,
    CryptoSnapshot,
    CryptoVenueObservation,
)
from .data import (
    DATA_QUALITY_PRIORITY,
    DataQualityStatus,
    EvidenceReference,
    SnapshotManifest,
    worst_data_quality_status,
)
from .data_health import (
    DataHealthCheck,
    DataHealthProbe,
    DataHealthReport,
    DataHealthSummary,
)
from .decisions import (
    DecisionActorType,
    DecisionCandidate,
    DecisionLifecycleEvent,
    DecisionRating,
    DecisionStatus,
)
from .equity_etf import (
    DatasetCoverage,
    EquityETFDataset,
    EquityETFSnapshotBundle,
    ETFProfile,
    FilingRecord,
    FundamentalFact,
    FundHolding,
    NewsRecord,
)
from .events import TERMINAL_RUN_EVENTS, RunEvent, RunEventType
from .evidence import EvidenceClaim, EvidenceGraph
from .factors import (
    DerivedFactorSnapshot,
    FactorSeriesInput,
    FactorWindowConfig,
    InstrumentFactors,
    MarketBreadth,
)
from .futures_reference import (
    FuturesContractReference,
    FuturesDataGap,
    FuturesGapKind,
    FuturesReferenceSnapshot,
    FuturesSessionWindow,
    GapDisposition,
    RollAdjustmentMethod,
    RolloverMetadata,
)
from .instruments import (
    AssetClass,
    InstrumentAliasContract,
    InstrumentContract,
    Tradability,
    normalize_instrument_alias,
)
from .jobs import JobKind, JobRecord, JobStatus
from .ledger import LedgerTransaction, LedgerTransactionType
from .policy import PolicyCheck, PolicyContract, PolicyResult
from .portfolio import CashBalance, PortfolioSnapshot, PositionSnapshot
from .runs import RunManifest, RunStatus
from .screening import (
    ScreenedStock,
    ScreeningExclusionCode,
    StockScreenerPolicy,
    StockScreeningExclusion,
    StockScreeningInput,
    StockUniverseSnapshot,
)
from .timeseries import (
    BenchmarkComparison,
    NormalizedTimeSeries,
    OHLCVBar,
    PriceBasis,
    PriceInterval,
    ReturnPoint,
    TimeSeriesStatistics,
    TimeSeriesView,
)

CONTRACT_REGISTRY = {
    contract.__name__: contract
    for contract in (
        InstrumentContract,
        InstrumentAliasContract,
        ArtifactManifest,
        SnapshotManifest,
        RunManifest,
        JobRecord,
        RunEvent,
        EvidenceReference,
        DecisionCandidate,
        PortfolioSnapshot,
        PolicyContract,
        PolicyCheck,
        NormalizedTimeSeries,
        TimeSeriesView,
        EquityETFSnapshotBundle,
        FuturesReferenceSnapshot,
        CryptoSnapshot,
        StockUniverseSnapshot,
        DerivedFactorSnapshot,
        DataHealthReport,
        EvidenceGraph,
        LedgerTransaction,
        DecisionLifecycleEvent,
    )
}

__all__ = [
    "SCHEMA_VERSION",
    "CONTRACT_REGISTRY",
    "AssetClass",
    "ArtifactKind",
    "ArtifactManifest",
    "BenchmarkComparison",
    "CashBalance",
    "ContentHash",
    "CryptoLiquidityMetrics",
    "CryptoQualityThresholds",
    "CryptoSnapshot",
    "CryptoVenueObservation",
    "DataQualityStatus",
    "DATA_QUALITY_PRIORITY",
    "DataHealthCheck",
    "DataHealthProbe",
    "DataHealthReport",
    "DataHealthSummary",
    "DecisionCandidate",
    "DecisionActorType",
    "DecisionLifecycleEvent",
    "DecisionRating",
    "DecisionStatus",
    "DerivedFactorSnapshot",
    "DatasetCoverage",
    "EvidenceReference",
    "EvidenceClaim",
    "EvidenceGraph",
    "EquityETFDataset",
    "EquityETFSnapshotBundle",
    "ETFProfile",
    "FilingRecord",
    "FundHolding",
    "FundamentalFact",
    "FuturesContractReference",
    "FuturesDataGap",
    "FuturesGapKind",
    "FuturesReferenceSnapshot",
    "FuturesSessionWindow",
    "FactorSeriesInput",
    "FactorWindowConfig",
    "GapDisposition",
    "InstrumentContract",
    "InstrumentAliasContract",
    "InstrumentFactors",
    "JobKind",
    "JobRecord",
    "JobStatus",
    "LedgerTransaction",
    "LedgerTransactionType",
    "PolicyCheck",
    "PolicyContract",
    "PolicyResult",
    "PortfolioSnapshot",
    "NormalizedTimeSeries",
    "MarketBreadth",
    "NewsRecord",
    "OHLCVBar",
    "PriceBasis",
    "PriceInterval",
    "ReturnPoint",
    "RollAdjustmentMethod",
    "RolloverMetadata",
    "PositionSnapshot",
    "RunManifest",
    "RunEvent",
    "RunEventType",
    "RunStatus",
    "ScreenedStock",
    "ScreeningExclusionCode",
    "SnapshotManifest",
    "StockScreenerPolicy",
    "StockScreeningExclusion",
    "StockScreeningInput",
    "StockUniverseSnapshot",
    "StrictContract",
    "TERMINAL_RUN_EVENTS",
    "Tradability",
    "TimeSeriesStatistics",
    "TimeSeriesView",
    "VersionedContract",
    "Weight",
    "normalize_instrument_alias",
    "worst_data_quality_status",
]
