import { fireEvent, render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, expect, it, vi } from 'vitest';
import RunForm from './RunForm';
import LanguageSwitch from './LanguageSwitch';
const catalog = [{ instrument_id: 'aapl', canonical_symbol: 'AAPL', display_name: 'Apple', asset_class: 'equity', tradability: 'investable', venue: 'NASDAQ', quote_currency: 'USD', timezone: 'America/New_York', session_calendar: 'XNAS', benchmark_symbol: 'SPY' }];
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status });
const source = { snapshot: { snapshot_id: 'source1', dataset: 'ohlcv.daily', vendor: 'TEST FIXTURE', source_end: '2026-09-01T00:00:00Z', quality_status: 'OK' }, metadata_eligible: true, ineligibility_reasons: [], supported_analysts: ['market'] };
afterEach(() => vi.unstubAllGlobals());
function setup(stale = false) {
  const fetch = vi.fn(async (url: string) => {
    if (url.includes('/portfolios?')) return json([{ portfolio_id: 'portfolio1', as_of: '2026-09-01T00:00:00Z', base_currency: 'USD', positions: [], cash: [], net_asset_value:'10000',realized_pnl:'0',unrealized_pnl:'0',content_hash:'fixture-hash' }]);
    if (url.includes('/policies?')) return json([{ policy_id: 'policy1', policy_version: '1', name: 'Fixture policy', asset_class: 'equity', effective_at: '2026-08-01T00:00:00Z', parameters: {} }]);
    if (url.includes('/analysis-profile')) return json({ name: 'equity', allowed_analysts: ['market', 'news'], investable: true });
    if (url.includes('/snapshots?')) return json([{ ...source, metadata_eligible: !stale, ineligibility_reasons: stale ? ['stale'] : [] }]);
    if (url.endsWith('/auth/csrf')) return json({ csrf_token: 'test-csrf' });
    return json({}, 503);
  });
  vi.stubGlobal('fetch', fetch); return fetch;
}
it('requires evidence and explicit paid-call authorization', async () => {
  setup(); const user = userEvent.setup(); render(<RunForm catalog={catalog} onClose={vi.fn()} onCreated={vi.fn()} />);
  const group = await screen.findByRole('group', { name: 'Price & trend' });
  expect((screen.getByRole('button', { name: 'Queue analysis' }) as HTMLButtonElement).disabled).toBe(true);
  await user.click(await within(group).findByRole('checkbox'));
  expect((screen.getByRole('button', { name: 'Queue analysis' }) as HTMLButtonElement).disabled).toBe(true);
  await user.click(screen.getByRole('checkbox', { name: /I authorize/ }));
  expect((screen.getByRole('button', { name: 'Queue analysis' }) as HTMLButtonElement).disabled).toBe(false);
});
it('keeps report language independent of UI and resets consent when changing generation language', async () => {
  const fetch = setup(); const user = userEvent.setup();
  render(<><LanguageSwitch /><RunForm catalog={catalog} onClose={vi.fn()} onCreated={vi.fn()} /></>);
  await user.click(await within(await screen.findByRole('group', { name: 'Price & trend' })).findByRole('checkbox'));
  await user.click(screen.getByRole('checkbox', { name: /I authorize/ }));
  expect((screen.getByLabelText('Report language') as HTMLSelectElement).value).toBe('en-vi');
  await user.click(screen.getByRole('button', { name: /VI/ }));
  expect((screen.getByLabelText('Ngôn ngữ báo cáo') as HTMLSelectElement).value).toBe('en-vi');
  expect((screen.getByRole('button', { name: 'Gửi phân tích' }) as HTMLButtonElement).disabled).toBe(false);
  await user.selectOptions(screen.getByLabelText('Ngôn ngữ báo cáo'), 'vi');
  expect((screen.getByRole('button', { name: 'Gửi phân tích' }) as HTMLButtonElement).disabled).toBe(true);
  await user.click(screen.getByRole('checkbox', { name: /Tôi cho phép/ }));
  await user.click(screen.getByRole('button', { name: 'Gửi phân tích' }));
  await screen.findByRole('alert');
  const calls = fetch.mock.calls as unknown as [string, RequestInit][];
  expect(JSON.parse(calls.find(([url]) => url.endsWith('/runs'))![1].body as string).report_language).toBe('vi');
});
it('withholds price snapshots from news and pins risk request to portfolio time', async () => {
  const fetch = setup(); const user = userEvent.setup(); render(<RunForm catalog={catalog} onClose={vi.fn()} onCreated={vi.fn()} />);
  const news = await screen.findByRole('group', {name:'News & events'});
  expect(within(news).queryByRole('checkbox')).toBeNull();
  expect(within(news).getByText('No suitable saved sources for this research area. It will not be included.')).toBeTruthy();
  await user.click(screen.getByRole('checkbox', {name:/Evaluate against my portfolio/}));
  await user.selectOptions(screen.getByLabelText('Portfolio snapshot'), 'portfolio1');
  expect((screen.getByLabelText('Research date & time (UTC)') as HTMLInputElement).value).toBe('2026-09-01T00:00');
  expect((screen.getByLabelText('Research date & time (UTC)') as HTMLInputElement).disabled).toBe(true);
  await user.selectOptions(screen.getByLabelText('Risk policy version'), 'policy1:1');
  await user.type(screen.getByLabelText('Owner target weight (0–1)'), '0.2');
  await user.click(await within(screen.getByRole('group', {name:'Price & trend'})).findByRole('checkbox'));
  await user.click(screen.getByRole('checkbox', {name:/I authorize/}));
  await user.click(screen.getByRole('button', {name:'Queue analysis'}));
  await screen.findByRole('alert');
  const calls = fetch.mock.calls as unknown as [string, RequestInit][];
  const body = JSON.parse(calls.find(([url]) => url.endsWith('/runs'))![1].body as string);
  expect(body.analysis_as_of).toBe('2026-09-01T00:00:00Z');
  expect(body.decision_inputs).toMatchObject({ portfolio_snapshot_id:'portfolio1', policy_id:'policy1', policy_version:'1', requested_target_weight:0.2, risk_snapshot_ids:[] });
});
it('uses explicit UTC date controls and keeps advanced freshness unchanged',async () => {
  const fetch = setup(); const user = userEvent.setup(); render(<RunForm catalog={catalog} onClose={vi.fn()} onCreated={vi.fn()} />);
  const date = screen.getByLabelText('Research date & time (UTC)');
  fireEvent.change(date,{target:{value:'2026-08-31T13:45:12.123'}});
  expect((screen.getByLabelText('Maximum source age (seconds)') as HTMLInputElement).value).toBe('604800');
  expect(screen.getByLabelText('Maximum source age (seconds)').closest('details')?.open).toBe(false);
  await user.click(await within(await screen.findByRole('group',{name:'Price & trend'})).findByRole('checkbox'));
  await user.click(screen.getByRole('checkbox',{name:/I authorize/}));
  await user.click(screen.getByRole('button',{name:'Queue analysis'}));
  await screen.findByRole('alert');
  const calls = fetch.mock.calls as unknown as [string, RequestInit][];
  const body = JSON.parse(calls.find(([url])=>url.endsWith('/runs'))![1].body as string);
  expect(body.analysis_as_of).toBe('2026-08-31T13:45:12.123Z');
  expect(body.decision_inputs.source_max_age_seconds).toEqual({market:604800});
  fireEvent.change(date,{target:{value:''}});
  expect((screen.getByRole('button',{name:'Queue analysis'}) as HTMLButtonElement).disabled).toBe(true);
});
it('disables stale evidence', async () => {
  setup(true); render(<RunForm catalog={catalog} onClose={vi.fn()} onCreated={vi.fn()} />);
  const group = await screen.findByRole('group', { name: 'Price & trend' });
  expect((await within(group).findByRole('checkbox') as HTMLInputElement).disabled).toBe(true);
});
it('reuses idempotency key on unchanged failed submission', async () => {
  const fetch = setup(); const user = userEvent.setup(); render(<RunForm catalog={catalog} onClose={vi.fn()} onCreated={vi.fn()} />);
  const group = await screen.findByRole('group', { name: 'Price & trend' });
  await user.click(await within(group).findByRole('checkbox'));
  await user.click(screen.getByRole('checkbox', { name: /I authorize/ }));
  await user.click(screen.getByRole('button', { name: 'Queue analysis' }));
  await screen.findByRole('alert');
  await user.click(screen.getByRole('button', { name: 'Queue analysis' }));
  await screen.findByRole('alert');
  const calls = fetch.mock.calls as unknown as [string, RequestInit][];
  const submissions = calls.filter(([url]) => url.endsWith('/runs'));
  expect(submissions).toHaveLength(2);
  expect(submissions[0][1].headers).toEqual(submissions[1][1].headers);
  expect(JSON.parse(submissions[0][1].body as string).selected_analysts).toEqual(['market']);
});
